name: Deploy Frontend to S3

on:
  push:
    branches:
      - main   # 你也可以改成 deployment 分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: client

      # 4. Build project
      - name: Build Vite project
        run: npm run build
        working-directory: client

      # 5. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6. Deploy to S3
      - name: Sync build to S3
        run: |
          aws s3 sync client/dist s3://${{ secrets.AWS_S3_BUCKET }} --delete

      # 7. Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
